# Generated by Django 2.2.3 on 2019-07-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_en',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='test_ru',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
