# Generated by Django 2.2.3 on 2019-07-20 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20190720_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortTest',
            fields=[
                ('test_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.Test')),
                ('test2', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'ordering': ['test2'],
            },
            bases=('testapp.test', models.Model),
        ),
    ]
